# Este es el código del workflow corregido y funcional para compilar un APK
# siempre y cuando el código del proyecto Android no tenga errores de compilación.

name: Build IslaAndroid APK

on:
  # Esto permite ejecutar el workflow manualmente desde la pestaña "Actions"
  workflow_dispatch:

jobs:
  build:
    # Ejecutar en el último Ubuntu disponible
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Paso 2: Configurar el entorno Java (JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Paso 3: Dar permisos de ejecución al script gradlew
      # El script gradlew está en la raíz del repositorio después del checkout
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Paso 4: Compilar el APK de depuración
      # Ejecuta las tareas clean y assembleDebug usando el wrapper de Gradle
      # Esto se ejecuta desde la raíz del repositorio
      - name: Build Debug APK
        run: ./gradlew clean assembleDebug

      # Paso 5: Subir el APK generado como un artefacto del workflow
      # La ruta es relativa a la raíz del repositorio, donde se espera que el build lo deje
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IslaAndroid-Debug-APK # Nombre con el que se guardará el artefacto
          path: app/build/outputs/apk/debug/app-debug.apk # Ruta al archivo APK
          retention-days: 5 # Por ejemplo, 5 días
